=== Daniel-Mora-Moreno/sistema-solar/xml/PLANETAS.DTD
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sistema-solar (planeta+)>
<!ELEMENT planeta (nombre, distancia, radio, gravedad?, rotacion?, orbita?, numero-satelites, satelite*)>
<!ATTLIST planeta
	enano (false | true) "false"> <!--w3schools.com/xml/xml_dtd_attributes.asp-->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT radio (#PCDATA)>
<!ELEMENT gravedad (#PCDATA)>
<!ELEMENT rotacion (#PCDATA)>
<!ATTLIST rotacion
	retrograda (false | true) "false">
<!ELEMENT orbita (#PCDATA)>
<!ELEMENT numero-satelites (#PCDATA)>
<!ELEMENT satelite (nombre, distancia, radio)>

=== Daniel-Mora-Moreno/sistema-solar/xml/validacion/PLANETAS.XML
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="planetas.xsl"?>
<!DOCTYPE sistema-solar SYSTEM "planetas.dtd">
<sistema-solar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "planetas.xsd">
	<planeta>
		<nombre>Mercurio</nombre>
			<!--obligatorio-->
		<distancia>58</distancia>
			<!--distancia al sol en millones de km, obligatorio-->
		<radio>2440</radio>
			<!--km, obligatorio-->
		<gravedad>3.70</gravedad>
			<!--m/s2, opcional-->
		<rotacion>58.65</rotacion>
			<!--días terrestres, opcional-->
		<orbita>0.24</orbita>
			<!--años terrestres, opcional-->
		<numero-satelites>0</numero-satelites>
			<!--obligatorio-->
	</planeta>
	<planeta>
		<nombre>Venus</nombre>
		<distancia>108</distancia>
		<radio>6052</radio>
		<gravedad>8.90</gravedad>
		<rotacion retrograda="true">243.02</rotacion>
		<orbita>0.62</orbita>
		<numero-satelites>0</numero-satelites>
	</planeta>
	<planeta>
		<nombre>Tierra</nombre>
		<distancia>150</distancia>
		<radio>6371</radio>
		<gravedad>9.81</gravedad>
		<rotacion>1</rotacion>
		<orbita>1</orbita>
		<numero-satelites>1</numero-satelites>
		<satelite>
			<nombre>Luna</nombre>
				<!--obligatorio-->
			<distancia>384</distancia>
				<!--distancia al planeta en miles de km, obligatorio-->
			<radio>1737</radio>
				<!--obligatorio-->
		</satelite>
	</planeta>
	<planeta>
		<nombre>Marte</nombre>
		<distancia>228</distancia>
		<radio>3389</radio>
		<gravedad>3.71</gravedad>
		<rotacion>1.03</rotacion>
		<orbita>1.88</orbita>
		<numero-satelites>2</numero-satelites>
	</planeta>
	<planeta>
		<nombre>Júpiter</nombre>
		<distancia>778</distancia>
		<radio>69911</radio>
		<gravedad>24.79</gravedad>
		<rotacion>0.41</rotacion>
		<orbita>11.86</orbita>
		<numero-satelites>67</numero-satelites>
		<satelite>
			<nombre>Ganímedes</nombre>
			<distancia>1070</distancia>
			<radio>2634</radio>
		</satelite>
		<satelite>
			<nombre>Calisto</nombre>
			<distancia>1883</distancia>
			<radio>2410</radio>
		</satelite>
		<satelite>
			<nombre>Ío</nombre>
			<distancia>422</distancia>
			<radio>1815</radio>
		</satelite>
		<satelite>
			<nombre>Europa</nombre>
			<distancia>671</distancia>
			<radio>1569</radio>
		</satelite>
	</planeta>
	<planeta>
		<nombre>Saturno</nombre>
		<distancia>1427</distancia>
		<radio>58232</radio>
		<gravedad>9.10</gravedad>
		<rotacion>0.44</rotacion>
		<orbita>29.45</orbita>
		<numero-satelites>62</numero-satelites>
		<satelite>
			<nombre>Titán</nombre>
			<distancia>1222</distancia>
			<radio>2576</radio>
		</satelite>
		<satelite>
			<nombre>Japeto</nombre>
			<distancia>3561</distancia>
			<radio>735</radio>
		</satelite>
		<satelite>
			<nombre>Tetis</nombre>
			<distancia>295</distancia>
			<radio>533</radio>
		</satelite>
		<satelite>
			<nombre>Dione</nombre>
			<distancia>377</distancia>
			<radio>562</radio>
		</satelite>
		<satelite>
			<nombre>Rea</nombre>
			<distancia>527</distancia>
			<radio>764</radio>
		</satelite>
	</planeta>
	<planeta>
		<nombre>Urano</nombre>
		<distancia>2871</distancia>
		<radio>25362</radio>
		<gravedad>7.80</gravedad>
		<rotacion retrograda="true">0.72</rotacion>
		<orbita>84.02</orbita>
		<numero-satelites>27</numero-satelites>
		<satelite>
			<nombre>Ariel</nombre>
			<distancia>191</distancia>
			<radio>579</radio>
		</satelite>
		<satelite>
			<nombre>Umbriel</nombre>
			<distancia>266</distancia>
			<radio>585</radio>
		</satelite>
		<satelite>
			<nombre>Titania</nombre>
			<distancia>436</distancia>
			<radio>789</radio>
		</satelite>
		<satelite>
			<nombre>Oberón</nombre>
			<distancia>583</distancia>
			<radio>761</radio>
		</satelite>
	</planeta>
	<planeta>
		<nombre>Neptuno</nombre>
		<distancia>4498</distancia>
		<radio>24622</radio>
		<gravedad>11.00</gravedad>
		<rotacion>0.67</rotacion>
		<orbita>163.80</orbita>
		<numero-satelites>14</numero-satelites>
		<satelite>
			<nombre>Tritón</nombre>
			<distancia>355</distancia>
			<radio>1353</radio>
		</satelite>
	</planeta>
	<planeta enano="true">
		<nombre>Ceres</nombre>
		<distancia>414</distancia>
		<radio>471</radio>
		<gravedad>0.27</gravedad>
		<rotacion>0.38</rotacion>
		<orbita>4.60</orbita>
		<numero-satelites>0</numero-satelites>
	</planeta>
	<planeta enano="true">
		<nombre>Plutón</nombre>
		<distancia>5906</distancia>
		<radio>1185</radio>
		<gravedad>0.60</gravedad>
		<rotacion retrograda="true">6.39</rotacion>
		<orbita>247.92</orbita>
		<numero-satelites>5</numero-satelites>
		<satelite>
			<nombre>Caronte</nombre>
			<distancia>18</distancia>
			<radio>603</radio>
		</satelite>
	</planeta>
	<planeta enano="true">
		<nombre>Haumea</nombre>
		<distancia>6484</distancia>
		<radio>575</radio>
		<gravedad>0.44</gravedad>
		<rotacion>0.17</rotacion>
		<orbita>285.40</orbita>
		<numero-satelites>2</numero-satelites>
	</planeta>
	<planeta enano="true">
		<nombre>Makemake</nombre>
		<distancia>6850</distancia>
		<radio>750</radio>
		<gravedad>0.50</gravedad>
		<orbita>309.90</orbita>
		<numero-satelites>1</numero-satelites>
	</planeta>
	<planeta enano="true">
		<nombre>Eris</nombre>
		<distancia>10210</distancia>
		<radio>1163</radio>
		<orbita>557.00</orbita>
		<numero-satelites>1</numero-satelites>
	</planeta>
</sistema-solar>
